#ifndef MATH_BACKEND_H
#define MATH_BACKEND_H

#if defined(HELIUS_MATH_BACKEND_CMSIS)
#define HELIUS_MATH_BACKEND_IS_CMSIS 1
#define HELIUS_MATH_BACKEND_IS_SCALAR 0
#else
#define HELIUS_MATH_BACKEND_IS_CMSIS 0
#define HELIUS_MATH_BACKEND_IS_SCALAR 1
#endif

#endif
